# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AllureLove-blog
email: clllove@yeah.net
description: > #个人博客学习
baseurl: ""
url: ""
github_username:  AllureLoveJL


# Author
author: lili
author_link: 

# Build settings
markdown: kramdown


collections:
  courses:
    output: true

gems:
  - jekyll-babel
